// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/theme_registry_gen.dart at 2026-03-05T01:59:55.499641
// Run: dart run tool/theme_registry_gen.dart

part of 'theme_catalog.dart';

// --------------------------------------------------------------------------
// 域分类列表（imports 在主库 theme_catalog.dart 中维护）
// --------------------------------------------------------------------------

const List<AppTheme> _universalThemes = [
  StarTrailsTheme(),
];

const List<AppTheme> _maimaiThemes = [
  CircleTheme(),
  DxTheme(),
];

const List<AppTheme> _chunithmThemes = [
  VerseTheme(),
];

// --------------------------------------------------------------------------
// 全局字典 (themeId → AppTheme instance)
// --------------------------------------------------------------------------

Map<String, AppTheme> _buildAllThemesRegistry() => {
  for (final t in [..._universalThemes, ..._maimaiThemes, ..._chunithmThemes])
    t.themeId: t,
};

// --------------------------------------------------------------------------
// 自动选取的全局默认主题（取 universalThemes 第一项）
// --------------------------------------------------------------------------

AppTheme get _defaultTheme => _universalThemes.first;
